# Generated by Django 3.0.9 on 2020-08-03 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20200803_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('quantity', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=200)),
                ('image1', models.ImageField(blank=True, upload_to='product_image1')),
                ('image2', models.ImageField(blank=True, upload_to='product_image2')),
                ('image3', models.ImageField(blank=True, upload_to='product_image3')),
                ('NGO', models.CharField(choices=[('Prayaas', 'Prayaas'), ('Pahal', 'Pahal'), ('NGO1', 'NGO1'), ('NGO2', 'NGO2')], default='Prayaas', max_length=30)),
                ('category', models.CharField(choices=[('book', 'book'), ('electronic', 'electronic'), ('furniture', 'furniture'), ('clothing', 'clothing'), ('sport', 'sport'), ('stationary', 'stationary'), ('daily_use', 'daily_use'), ('other', 'other')], default='stationary', max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
