# Generated by Django 3.0.9 on 2020-08-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_donate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='category',
            field=models.CharField(choices=[('book', 'book'), ('electronic', 'electronic'), ('furniture', 'furniture'), ('clothing', 'clothing'), ('sport', 'sport'), ('stationary', 'stationary'), ('daily_use', 'daily_use'), ('other', 'other')], default='stationary', max_length=30, null=True),
        ),
    ]
